const ActionTypes = {
    SET_ALL_PROJECTS: 'SET_ALL_PROJECTS',
    ADD_PROJECT: 'ADD_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    GET_PROJECT_VIEW: 'GET_PROJECT_VIEW',
    DELETE_PROJECT_VIEW: 'DELETE_PROJECT_VIEW',
    SEARCH_PROJECTS: 'SEARCH_PROJECTS'
}

export default ActionTypes